package com.example.javaspringmysql.service;

import java.util.ArrayList;
import java.util.Date;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.javaspringmysql.dto.Profile;
import com.example.javaspringmysql.repository.ProfileRepository;
import com.example.javaspringmysql.util.IdUtilities;

@Service
public class ProfileService {

    @Autowired
    private ProfileRepository profileRepository;

    public ArrayList<Profile> get() {
        return (ArrayList<Profile>)this.profileRepository.findAll();
    }

    public Profile post(Profile profile) {
        if(profile.getUserId() == null) {
            // Autogenerated id 
            profile.setUserId(IdUtilities.generateId());
        }
        Date date = new Date();  
        // Automatically registered init and lastMod dates  
        profile.setInitDate(date);  
        profile.setLastModDate(date);
        return profileRepository.save(profile);
    }

    public Profile put(Profile profile, String userId) {
        Date date = new Date();
        // initDate must not be altered
        profile.setInitDate(this.getByKey(userId).get().getInitDate());
        // register automatically the latest lastModDate 
        profile.setLastModDate(date);
        return profileRepository.save(profile);
    }

    public void delete(String userId) {
        profileRepository.deleteById(userId);
    }

    public Optional<Profile> getByKey(String userId) {
        return profileRepository.findById(userId);
    }
    
}
